### ISSUE TITLE
Make requests-hawk compatible with python3.

### ISSUE THREAD

**Issue by Natim** [mozilla-services/requests-hawk#2]

**Comment by volphy** [comment]
Is current release of requests-hawk (1.0.0) still not compatible with Python 3?

I am trying to run a simple script and receive the following error message:
```
$ ./test.py
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.7) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
```

Any idea?

**Comment by Natim** [comment]
Hello @volphy thank your for your message. I created the following PR #22 to add Python 3 support.

Can you try it on your project?

Best regards,

Rémy

**Comment by volphy** [comment]
It seems to work now. Thanks.

I have tested it against Python 3.7.3 and requests 2.22.0.
