### ISSUE TITLE
New release with Python 3.x support?

### ISSUE THREAD

**Issue by volphy** [mozilla-services/requests-hawk#23]
Would it be possible to release a new version (e.g. 1.0.1) with Python 3.x support?

Python 3.8 support is already available in master branch.

**Comment by Natim** [comment]
@volphy I just released 1.0.1 on Pypi.

@rfk I have a couple of commit and a tag to push but I don't seem to have write permission on this repository anymore. Could you add me back?

**Comment by rfk** [comment]
>  Could you add me back?

@Natim I've invited you, let me know if that doesn't come through for some reason.

**Comment by Natim** [comment]
It worked, thanks!
