### ISSUE TITLE
resp is not defined

### ISSUE THREAD

**Issue by Ming203** [mozilla-services/requests-hawk#33]
import requests
from requests_hawk import HawkAuth

hawk_auth = HawkAuth(
    hawk_session=resp.headers['hawk-session-token'],
    server_url=self.server_url
)
requests.post("/url", auth=hawk_auth)

when I run this code with own session token and server url, response is resp is not defined

**Comment by Natim** [comment]
`resp.headers['hawk-session-token'],`
