### ISSUE TITLE
Make instantiation with credentials simpler/cleaner

### ISSUE THREAD

**Issue by edmorley** [mozilla-services/requests-hawk#8]
We've just started to use Hawk for the Treeherder API and so are having to add support to our Python client that we make available for people to interact with the API, as well as update documentation for it.

The current WIP docs for how people should use our Python client, has examples like:
```python
from requests_hawk import HawkAuth
from thclient import TreeherderClient
...
auth = HawkAuth(credentials={
    'id': 'your-treeherder-client-id',
    'key': 'your-secret',
    'algorithm': 'sha256'
})
client = TreeherderClient(protocol='https', host='treeherder.mozilla.org', auth=auth)
client.post_collection('mozilla-central', tjc)
```
This is more verbose than I'd like (eg: users of our client shouldn't have to know we're using sha256) and passing the credentials as a dict doesn't seem very clean, so I was contemplating wrapping HawkAuth like so in our client code:
```python
class TreeherderHawkAuth(HawkAuth):
    """Thin wrapper around HawkAuth to reduce boilerplate."""
    def __init__(self, client_id, secret):
        credentials = {
            'id': client_id,
            'key': secret,
            'algorithm': 'sha256'
        }
        return super(TreeherderHawkAuth, self).__init__(credentials=credentials)
```
So instead the example would become:
```python
from thclient import TreeherderClient, TreeherderHawkAuth
...
auth = TreeherderHawkAuth('your-treeherder-client-id', 'your-secret')
client = TreeherderClient(protocol='https', host='treeherder.mozilla.org', auth=auth)
client.post_collection('mozilla-central', tjc)
```

However we then have a wrapper around a wrapper whose purpose was to make using Hawk with requests simpler, which seems to defeat the point a bit.

Would you be open to making changes to make this unnecessary? (eg defaulting to 'sha256' if no algorithm specified, being able to pass the credentials in a nicer form than a dict etc. eg a `HawkAuth(client_id='foo', secret='bar')` or `HawkAuth.from_credentials('foo', 'bar')`).

Thanks :-)

**Comment by Natim** [comment]
What about making it even simpler like:

```
from thclient import TreeherderClient
client = TreeherderClient(protocol='https', host='treeherder.mozilla.org', auth=('your-treeherder-client-id', 'your-secret'))
```
And then building the HawkAuth inside the TreeherderClient constructor?

**Comment by edmorley** [comment]
We currently support multiple forms of authentication, the `auth` argument to TreeherderClient is a requests `auth` object. I guess we could move away from that model, but either way the current HawkAuth API does seem like it could be cleaner :-)

**Comment by Natim** [comment]
It is what I was thinking.
I like the ``HawkAuth(id='foo', key='bar')``.

Would you be able to file a Pull-Request to contribute this change?

**Comment by edmorley** [comment]
Yeah I like that - I'll submit a PR. We'll have to use something other than `id` since it's a built-in - do you prefer `hawk_id` or `client_id` or ...?

**Comment by Natim** [comment]
Or maybe we could support this: ``HawkAuth(credentials=('your-treeherder-client-id', 'your-secret'))`` with an optional third parameter in the tuple for the algorithm.

**Comment by ametaireau** [comment]
I actually quite like having the keys, otherwise we can mix them up.

What about ```
HawkAuth(client_id=1324, client_key='mykey')
```

And effectively defaulting to sha256 if not specified?

**Comment by Natim** [comment]
Ok it works for me :+1:

**Comment by edmorley** [comment]
I'm happy to create a PR for this, which of these options would you prefer:
1. Remove the `credentials` param and replace it with the `client_id`/`client_key` params from above, and bump the major version.
2. Same as [1], except only indicate in the docs that the `credentials` param is deprecated, rather than removing it.
3. Support both `credentials` and `client_*` long term.
(Plus for all three of these, `hawk_session` will still be supported).

I have a preference for either [1] or [2].

**Comment by edmorley** [comment]
Also I wonder if it would be cleaner to use either of these patterns, rather than trying to enforce manually that the arguments provided were either `hawk_session` OR `credentials` OR (`client_id` AND `client_key`)?

Example (if we take hawk_session as the least common case):
```python
auth = HawkAuth('client-id-foo', 'client-key-bar')
auth = HawkAuth.from_hawk_session('hawk-session-baz')
```

Or if you think hawk_session is the common case, we could do it like:
```python
auth = HawkAuth('hawk-session-baz')
auth = HawkAuth.from_credentials('client-id-foo', 'client-key-bar')
```

Thoughts? :-)

**Comment by Natim** [comment]
I think we should keep supporting both.

**Comment by edmorley** [comment]
We shouldn't use `id` since there's a python builtin with the same name. As such, `**credentials` wouldn't work anyway. Also is there a reason to support it (other than avoiding people having to make a code change?) - eg does some other package return a `credentials` object?

With all the options above I was also going to support passing `algorithm`, but just have it default to `sha256`.

Perhaps a PR would be easier to discuss after all?

**Comment by almet** [comment]
In the function call, you probably won't have any shadowing problem with the fact that `id` is builtin in python, so in my opinion it's okay to pass all the arguments with **credentials.

**Comment by almet** [comment]
If that causes a problem, we could also consider renaming the `id` argument into `client_id`.

**Comment by almet** [comment]
conceptually, having the `id` shadowed isn't a problem from the real world, especially because in this codebase, we probably will never need to use the `id` builtin, and even if we need to, we could access it with the `builtin` module.

**Comment by Natim** [comment]
It is important to support the credentials object because it is the standard way to give credentials to HawkAuth.

I do not think we will need the id ``builtins`` in the code of HawkAuth and if we do we can probably use ``builtins.id`` instead so we should be safe using ``id`` here.

Also IMHO, the API will be much easier to understand for people if we keep up with the standard way of defining the Hawk credentials (id/key/algorithm)

**Comment by edmorley** [comment]
> Also IMHO, the API will be much easier to understand for people if we keep up with the standard way of defining the Hawk credentials (id/key/algorithm)

Ok, that makes more sense, if upstream Hawk does it. It seemed like it was some requests-hawk specific structure, that was all.

In which case I don't know whether it's worth fixing this at all. (I probably wouldn't have opened the issue if I'd have know upstream did the same).

**Comment by Natim** [comment]
It doesn't prevent from using a more pythonic way, reason why I like your proposal of doing:

    HawkAuth(client_id, client_key, algorithm)

I was voicing in to propose that we could also support:

    HawkAuth(**credentials)

So that it helps people from moving from the old to the new format.
